### ISSUE TITLE
Where can I get the imagenet segmentation dataset?

### ISSUE THREAD

**Issue by jfloveu** [hila-chefer/Transformer-Explainability#12]
**❔Question**
Hello,
I think it's a very interestring work! But I want to konw where I can get the dataset in "reproducing results on ViT", for example, "gtsegs_ijcv.mat".
I hope for your help. Thanks!

**Comment by hila-chefer** [comment]
Hi @jfloveu thanks for your interest in our work!
IMO- we downloaded the segmentation from here:
https://github.com/aravindhm/deconvnet_analysis
section 7, but I see the link is now corrupt. 
I’ll check if I can either find you another link or upload it somewhere so you can download it.
I’m leaving this issue open, will get back to you with an answer.

**Comment by jfloveu** [comment]
Thanks for your reply. Of course, other datasets are also OK, as long as they run on your code, which will be more helpful for me to understand how the code works.

**Comment by hila-chefer** [comment]
Temporarily, I uploaded the file to an online service: https://easyupload.io/zkelad which will be available for the next 30 days.
I'm finding out if we can upload it to a server from the university so anyone can download it at any time :)
this link should work for now, but I'm going to leave this issue open until we find a permanent solution :)
thanks for bringing my attention to this issue! I hope this helps for now...

**Comment by hila-chefer** [comment]
Hi @jfloveu,

we are contacting the original authors of the paper we used to get this data.
Hopefully, they can share a new and valid link.
Since it’s not our data, we cannot upload it to our university servers. I’ll update here once we have a response from them.

**Comment by hila-chefer** [comment]
@jfloveu an official link:
http://calvin-vision.net/bigstuff/proj-imagenet/data/gtsegs_ijcv.mat
Taken from:
http://calvin-vision.net/bigstuff/proj-imagenet/page/index.html
