### ISSUE TITLE
Is that possible to calculate the relevance of recurrent neural network (RNN)?

### ISSUE THREAD

**Issue by StOnEGiggity** [hila-chefer/Transformer-Explainability#13]
Hi, thanks for your excellent work and source code.

I want to visualize my own attention-based architecture, which involves RNN. While implementing this, I find one question: Is it possible to calculate and propagate the relevance of RNN? If the answer is YES, is there any detailed suggestion?

Thanks again for your work and suggestions.

Best wishes

**Comment by hila-chefer** [comment]
Hi @StOnEGiggity thanks for your interest in our work, and for your kind words :)
Yes of course you can implement LRP on any architecture. I suggest to look at [innvestigate](https://github.com/albermax/innvestigate) for inspiration, It’s a great resource for implementing LRP (we use the alpha beta version for alpha=1, beta=0).
Other than that, I would also offer a spoiler alert and say that we have another work coming up very soon that generalizes our method (to other forms of attention, not just self attention) and may be easier to implement.
Hope you’ll stay tuned for our next work and find it helpful and useful :) 

Feel free to ask for clarifications if needed.

**Comment by StOnEGiggity** [comment]
Thanks for your fast reply!

I will study the proposed repo, and I also find one repo specifically designed for LSTM (https://github.com/ArrasL/LRP_for_LSTM). I will try to implement it for my customed architecture.

I would close this issue temporarily, and anyone could reopen this issue if he has the same problem.
