### ISSUE TITLE
how to integrate CLIP model and find CLIP attention map?

### ISSUE THREAD

**Issue by maryamag85** [hila-chefer/Transformer-Explainability#14]
Thanks for your great work.
Is there any attempt on integrating CLIP into this model?
I would like to see the attention map of the CLIP model (ViT base)

**Comment by hila-chefer** [comment]
Hi @maryamag85, thanks for your interest in our work!
Currently, there's no specific effort to implement our method for CLIP. However, it should be applicable by back-propagating LRP and gradients to the attention layers of both the image and the text, and then using our aggregation.
We also have a new work coming out really soon, with a simplified and extended version of our method which doesn't use LRP so it's much easier to implement, and also works for non-self-attention such as encoder-decoder attention!
Maybe that can help you with your CLIP visualization? Hope you stay tuned :)

**Comment by hila-chefer** [comment]
Hi @maryamag85, great news- we have added CLIP to our [new repo](https://github.com/hila-chefer/Transformer-MM-Explainability) with a colab notebook to run examples! hope this helps :)

**Comment by maryamag85** [comment]
awesome news! thanks
