### ISSUE TITLE
Abs in Add Normalization

### ISSUE THREAD

**Issue by ChuanyangZheng** [hila-chefer/Transformer-Explainability#15]
Thank you for your interesting work! 
I have read your code and get puzzled in [add relprop](https://github.com/hila-chefer/Transformer-Explainability/blob/f085594997553b46ce026ad5478ea01267ed9ed7/modules/layers_ours.py#L112):
```python
        a_sum = a.sum()
        b_sum = b.sum()

        a_fact = safe_divide(a_sum.abs(), a_sum.abs() + b_sum.abs()) * R.sum()
        b_fact = safe_divide(b_sum.abs(), a_sum.abs() + b_sum.abs()) * R.sum()
```
According normalization in your paper, it should do a.abs() first, then sum them up as a_sum=a.sum(), but you do it reversely in code?

**Comment by hila-chefer** [comment]
Hi @ChuanyangZheng, thanks for your interest in our work :)
While I didn't really understand your confusion, I'll try to address the normalization implementation in general, hopefully, that will clarify:
this code you refer to here:
```
        a_sum = a.sum()
        b_sum = b.sum()

        a_fact = safe_divide(a_sum.abs(), a_sum.abs() + b_sum.abs()) * R.sum()
        b_fact = safe_divide(b_sum.abs(), a_sum.abs() + b_sum.abs()) * R.sum()
```
is implementing this part of the normalization formula:
![norm1](https://user-images.githubusercontent.com/38704554/112584863-bce66e00-8e09-11eb-9ee6-52f068dc808a.PNG)

While the other code:
```
        a = a * safe_divide(a_fact, a.sum())
        b = b * safe_divide(b_fact, b.sum())
```
implements:
![norm2](https://user-images.githubusercontent.com/38704554/112584979-046cfa00-8e0a-11eb-96a2-2fdd03f42c79.PNG)
this part and of course multiplies by the already computed a_fact, b_fact.
I hope this helps and clarifies things, please feel free to ask for further clarifications.

**Comment by hila-chefer** [comment]
Hi @ChuanyangZheng, thanks for your interest! Nice catch :)
It's a mistake in the paper, will be fixed for camera ready (CVPR'21).
