### ISSUE TITLE
New post's url about the paper can not be accessed

### ISSUE THREAD

**Issue by NickChang97** [hila-chefer/Transformer-Explainability#18]
Hi, this url  https://analyticsindiamag.com/compute-relevancy-of-transformer-networks-via-novel-interpretable-transformer/   may be broken.

**Comment by hila-chefer** [comment]
Hi @NickChang97, thanks for your interest in our work!
I’m able to follow this link to the blog post. Could you try again?

**Comment by NickChang97** [comment]
Really thanks for your reply, it was something wrong with my network,  I can access it now.
