### ISSUE TITLE
missing link to paper

### ISSUE THREAD

**Issue by eyaler** [hila-chefer/Transformer-Explainability#2]
https://arxiv.org/abs/2012.09838

**Comment by hila-chefer** [comment]
Absolutely right, thanks for that, I’ll add it ASAP @eyaler

**Comment by gao-shi** [comment]
when i open the website,
"
Access Denied
Sadly, you do not currently appear to have permission to access https://arxiv.org/abs/2012.09838
"

**Comment by hila-chefer** [comment]
Hi @gao-shi thanks for your interest in our work!
I’m actually able to use this link, without an access denied message, you can also try this link which is directly to the paper (takes a few seconds to load):
https://arxiv.org/pdf/2012.09838v1.pdf
let me know if this solves the issue.

**Comment by gao-shi** [comment]
Now I can access the paper, thx!
