### ISSUE TITLE
what should i do when trying this visualization method on cifar dataset

### ISSUE THREAD

**Issue by caposerenity** [hila-chefer/Transformer-Explainability#20]
Hi,
i'm wondering how to modify the generate_visualization( ) method in the demo when trying this on CIFAR-100 with img_size=32*32 instead of 224*224
due to limit of my GPU memory, i failed setting the input size to my vit model as 224

Thanks!

**Comment by hila-chefer** [comment]
Hi @caposerenity , thanks for your interest in our work! Apologies for the delayed response.
Of course you can, I think all you need to do is to load different weights to our [ViT implementation](https://github.com/hila-chefer/Transformer-Explainability/blob/main/baselines/ViT/ViT_LRP.py), see [this function for example](https://github.com/hila-chefer/Transformer-Explainability/blob/main/baselines/ViT/ViT_LRP.py#L410). After you load your own pretrained weights, just modify the reshapes in the  `generate_visualization( )` function, `transformer_attribution = transformer_attribution.reshape(1, 1, 14, 14)` this line reshapes to the shape of the patch dimensions, and later interpolate to 32x32.

I hope this helps, let me know if you require any clarifications.
Also, if this works, I encourage you to add a PR with your changes for other people to use :)
