### ISSUE TITLE
gtsegs_ijcv.mat

### ISSUE THREAD

**Issue by torchmyheart** [hila-chefer/Transformer-Explainability#33]
Hello, thank you very much for sharing your work. I have a few questions and look forward to your answers. How do I get the gtsegs_ijcv.mat file? As far as I know, imagenet does not seem to have segmentation labels. Thanks again, and look forward to your reply.

**Comment by hila-chefer** [comment]
Hi @coderrubbish, thanks for your interest in our work!
Please refer to the [results reproduction](https://github.com/hila-chefer/Transformer-Explainability#reproducing-results-on-vit) section of our README, there's a [link to download the data](http://calvin-vision.net/bigstuff/proj-imagenet/data/gtsegs_ijcv.mat).

Best,
Hila.
