### ISSUE TITLE
Where can I download "imagenet_validation_directory"？

### ISSUE THREAD

**Issue by XuehuiPeng** [hila-chefer/Transformer-Explainability#41]
Hello!
I'm very interested in your work!
But I have trouble in running the Perturbation Results in Readme, because of lacking the file!
So, where can I download "imagenet_validation_directory"?
Thank you in advance for your convenience!

**Comment by hila-chefer** [comment]
Hi @HandleI, thanks for your interest in our work!
You'll need to download the [ImageNet  ILSVRC2012 dataset](https://image-net.org/challenges/LSVRC/2012/index.php).

Best,
Hila.
