### ISSUE TITLE
What is difference between Deit and ViT models here? They looks like the same?

### ISSUE THREAD

**Issue by szubing** [hila-chefer/Transformer-Explainability#45]
I have not found any difference between vit_base_patch16_224 and deit_base_patch16_224 in ViT_LRP.py? What makes they differerent?

**Comment by hila-chefer** [comment]
Hi @szubing, thanks for your interest!

The two models use the same architecture but were trained differently. DeiT uses knowledge distillation while ViT uses plain supervision for training. I recommend reading the papers to understand the differences.
