### ISSUE TITLE
using finetuned ViT weights/model from the Torchvision library

### ISSUE THREAD

**Issue by PedroDKE** [hila-chefer/Transformer-Explainability#49]
Hey, first of thanks for all the work in this repo!

I'm trying to adjust the sample notebook to work with ViT from the torchvision library,
As you might think already, im getting the "AttributeError: 'VisionTransformer' object has no attribute 'relprop' " error. 
As suggested in #30 i should pass/load the weights to the modified implementation of this repo. 
I can not figure out how i'm supposed to do this? more specifically: when calling `vit_LRP(pretrained=True)` how should i pass my own weights/ Torchvision model to be used?

**Comment by hila-chefer** [comment]
Hi @PedroDKE, thanks for your interest in our work!

As mentioned in [this answer](https://github.com/hila-chefer/Transformer-Explainability/issues/11) you can load your own weights as long as they are compatible with the implementation from timm.

does this help?

**Comment by PedroDKE** [comment]
Will have a look, thank you! :)

**Comment by hila-chefer** [comment]
Closing this issue for now, please reopen if necessary.
