### ISSUE TITLE
if it is possible to support DETR in the future

### ISSUE THREAD

**Issue by dc-cheny** [hila-chefer/Transformer-Explainability#5]
I want to know when to provide a visual template of a target detection model like DETR? thx~

**Comment by hila-chefer** [comment]
Hi @dc-cheny!
Could you please clarify your question? I'm afraid I didn't understand you.
Do you want to use our method on DETR? Are you asking if we're planning to support DETR in the future?
Thanks :)

**Comment by dc-cheny** [comment]
> Hi @dc-cheny!
> Could you please clarify your question? I'm afraid I didn't understand you.
> Do you want to use our method on DETR? Are you asking if we're planning to support DETR in the future?
> Thanks :)

sry, just as your words, i want to ask if it is possible to support detr in the future?  
I am very interested in the method of this paper and at the same time I am also using detr recently, thanks for reply~

**Comment by hila-chefer** [comment]
I'm glad that you find our work interesting! :) 
We are currently planning on expanding our work and DETR is very high on our list (alongside VisualBERT and other multimodal models).
Stay tuned :) I'll leave this issue open and close it once we expand to DETR as well.

**Comment by dc-cheny** [comment]
> I'm glad that you find our work interesting! :)
> We are currently planning on expanding our work and DETR is very high on our list (alongside VisualBERT and other multimodal models).
> Stay tuned :) I'll leave this issue open and close it once we expand to DETR as well.

Sounds exciting. I will keep following

**Comment by hila-chefer** [comment]
[We now support DETR, LXMERT, VisualBERT](https://github.com/hila-chefer/Transformer-MM-Explainability)! Check out our new method + new paper :) it is very simple- we remove the LRP component, and it is also applicable to co-attention and encoder-decoder networks :)

**Comment by dc-cheny** [comment]
> [We now support DETR, LXMERT, VisualBERT](https://github.com/hila-chefer/Transformer-MM-Explainability)! Check out our new method + new paper :) it is very simple- we remove the LRP component, and it is also applicable to co-attention and encoder-decoder networks :)

I feel so excited to hear this news! I will try your new method recently, thanks for noticing :)
