### ISSUE TITLE
Extension to other huggingface transformer models? 

### ISSUE THREAD

**Issue by mollie9523** [hila-chefer/Transformer-Explainability#54]
Hi, 

I am interested to apply this transformer explainability to other huggingface transformer models such as Swin Transformer and CvT. How can I do so? 

Thank you.

**Comment by hila-chefer** [comment]
Hi @cactusmomo, thanks for your interest!
As of now, the models in this repo are the models we support, expanding to swin Transformers is an interesting and non trivial effort (see previous issues) if you come up with something for that- please share :)
