### ISSUE TITLE
Trying this with vit-pytorch and hugging face transformer

### ISSUE THREAD

**Issue by krishnaadithya** [hila-chefer/Transformer-Explainability#56]
AttributeError: 'ViT' object has no attribute 'relprop'

hugging face: 

model = ViTForImageClassification.from_pretrained('google/vit-base-patch16-224').cuda()
AttributeError: 'ViTForImageClassification' object has no attribute 'relprop'

**Comment by Song-z-h** [comment]
How did you solve it?

**Comment by yumikim381** [comment]
Same problem here, did you solve it?
