### ISSUE TITLE
Multi-card training out of memory

### ISSUE THREAD

**Issue by lingorX** [hila-chefer/Transformer-Explainability#7]
Hi, first thank you for your excellent work, it makes sense and helps me a lot!

But I come across some trouble when trying to fine-tune ViT with another dataset.
I used four 2080ti to train it (torch.nn.DataParallel(model).cuda()), but the memory kept increasing, as if the space taken up after the previous inference and backward operations had not been released. 

It is worth noting that single card works well.

There may be problems with the hook-related functions in the code as my training code executed properly on another [ViT model](https://github.com/jeonsworld/ViT-pytorch) with multiple cards.
I'm trying to solve it...,  but I think I need your help.

**Comment by hila-chefer** [comment]
Hi @0liliulei, glad to hear you find our work useful!
Our method is really meant to be a post hoc analysis, and I haven’t tried to fine tune ViT with our code. 
I would recommend fine tuning the ViT code without the hooks, saving the weights you got and then using our code for analysis.
Is there any specific reason you require to train the model with our code?

**Comment by lingorX** [comment]
Yes, it is practical to write a second set of code for training, thank you for your reply.

**Comment by hila-chefer** [comment]
@0liliulei sure, no problem.
Once you have your weights, you can add your new model to our code similar to [what I did with Deit](https://github.com/hila-chefer/Transformer-Explainability/blob/main/baselines/ViT/ViT_LRP.py#L427), and then you can use the [Deit notebook](https://github.com/hila-chefer/Transformer-Explainability/blob/main/DeiT_example.ipynb) as template, where in `from baselines.ViT.ViT_LRP import deit_base_patch16_224 as vit_LRP` you can replace `deit_base_patch16_224` with your function to load pretrained weights and it should work...
